title: Alec Barber # your name (or website title) here
logo: "/images/alec.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computer and Electronic Engineering Scholar | TWC Lead Educator | Bayesian Transfer Learning and Machine Learning
  <br><br>
  Keen interest in Bayesian methods, History and software development.
  <br><br>
  <a href="https://www.linkedin.com/in/alec-barber/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
